---
development:
  dialect: postgres
  database: cluster_processor_service_development
  user: postgress
  password: postgress
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/cluster_processor_service_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/cluster_processor_service_production?sslmode=disable"}}
