version: '3.7'

services:
  postgresql:
    image: 'bitnami/postgresql:12.4.0'
    restart: unless-stopped
    env_file:
      - database.local.env # configure postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8085:8080